server.port=5001

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI}

# JWT Configuration
jwt.secret=${JWT_SECRET}

# Encryption Key (32 bytes hex = 64 characters)
encryption.key=${ENCRYPTION_KEY}